# Generated by YCM Generator at 2015-10-15 14:23:18.300137

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-x',
    'c++',
    '-DCC_ENABLE_BOX2D_INTEGRATION=0',
    '-DCC_ENABLE_BULLET_INTEGRATION=1',
    '-DCC_ENABLE_CHIPMUNK_INTEGRATION=1',
    '-DCC_TARGET_OS_MAC',
    '-DCC_USE_NAVMESH=1',
    '-DCC_USE_PHYSICS=1',
    '-DCC_USE_WEBP=1',
    '-DCOCOS2D_DEBUG=1',
    '-DCP_USE_CGPOINTS=0',
    '-DUSE_FILE32API',
    '-D_DARWIN_C_SOURCE',
    '-D_POSIX_C_SOURCE=200809L',
    '-I/System/Library/Frameworks',
    '-I/Users/guanghui/cocos2d-x',
    '-I/Users/guanghui/cocos2d-x/coco-DCC_ENABLE_BOX2D_INTEGRATION=0',
    '-I/Users/guanghui/cocos2d-x/cocos',
    '-I/Users/guanghui/cocos2d-x/cocos/../../extensions',
    '-I/Users/guanghui/cocos2d-x/cocos/../external/ConvertUTF',
    '-I/Users/guanghui/cocos2d-x/cocos/../external/clipper',
    '-I/Users/guanghui/cocos2d-x/cocos/../external/edtaa3func',
    '-I/Users/guanghui/cocos2d-x/cocos/../external/poly2tri',
    '-I/Users/guanghui/cocos2d-x/cocos/../external/poly2tri/common',
    '-I/Users/guanghui/cocos2d-x/cocos/../external/poly2tri/sweep',
    '-I/Users/guanghui/cocos2d-x/cocos/../external/xxtea',
    '-I/Users/guanghui/cocos2d-x/cocos/2d',
    '-I/Users/guanghui/cocos2d-x/cocos/3d',
    '-I/Users/guanghui/cocos2d-x/cocos/audio/incl',
    '-I/Users/guanghui/cocos2d-x/cocos/audio/incl-DCC_ENABLE_BOX2D_INTEGRATION=0',
    '-I/Users/guanghui/cocos2d-x/cocos/audio/inclUsers/guanghui/cocos2d-x/extensions/Particle3D/PU/CCPUVelocityMatchingAffectorTranslator.cpp',
    '-I/Users/guanghui/cocos2d-x/cocos/audio/inclocos2d-x/extensions/Particle3D/PU/CCPUForceFieldAffector.cpp',
    '-I/Users/guanghui/cocos2d-x/cocos/audio/incls/platform/desktop/CCGLViewImpl-desktop.cpp',
    '-I/Users/guanghui/cocos2d-x/cocos/audio/include',
    '-I/Users/guanghui/cocos2d-x/cocos/base',
    '-I/Users/guanghui/cocos2d-x/cocos/editor-support',
    '-I/Users/guanghui/cocos2d-x/cocos/editor-support/cocosbuilder',
    '-I/Users/guanghui/cocos2d-x/cocos/editor-support/cocostudio',
    '-I/Users/guanghui/cocos2d-x/cocos/editor-support/cocostudio/ActionTimeline',
    '-I/Users/guanghui/cocos2d-x/cocos/editor-support/spine',
    '-I/Users/guanghui/cocos2d-x/cocos/navmesh',
    '-I/Users/guanghui/cocos2d-x/cocos/physics3d',
    '-I/Users/guanghui/cocos2d-x/cocos/platform',
    '-I/Users/guanghui/cocos2d-x/cocos/platform/desktop',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../-DCC_ENABLE_BOX2D_INTEGRATION=0',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../-DCC_ENABLE_BOX2D_INTEGRATION=0',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../../external',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/2d',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/3d',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/audio/include',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/base',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/editor-support',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/editor-support/cocosbuilder',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/editor-support/cocostudio',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/editor-support/spine',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/navmesh',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/network',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/physics3d',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/platform',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/storage',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../cocos/ui',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../extensions',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../external',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../external/chipmunk/include/chipmunk',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../../external/spidermonkey/include/mac',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/../../external/spidermonkey/include/mac',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/auto',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/manual',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/manual/cocostudio',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/manual/navmesh',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/js-bindings/manual/spine',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/lua-bindings/auto',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/lua-bindings/manual',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/lua-bindings/manual/cocos2d',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/lua-bindings/manual/cocostudio',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/lua-bindings/manual/extension',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/lua-bindings/manual/navmesh',
    '-I/Users/guanghui/cocos2d-x/cocos/scripting/lua-bindings/manual/ui',
    '-I/Users/guanghui/cocos2d-x/cocos/ui',
    '-I/Users/guanghui/cocos2d-x/deprecated',
    '-I/Users/guanghui/cocos2d-x/extensions',
    '-I/Users/guanghui/cocos2d-x/external',
    '-I/Users/guanghui/cocos2d-x/external/bullet',
    '-I/Users/guanghui/cocos2d-x/external/bullet/..',
    '-I/Users/guanghui/cocos2d-x/external/chipmunk/include/chipmunk',
    '-I/Users/guanghui/cocos2d-x/external/curl/include/mac',
    '-I/Users/guanghui/cocos2d-x/external/flatbuffers',
    '-I/Users/guanghui/cocos2d-x/external/freetype2/include/mac/freetype2',
    '-I/Users/guanghui/cocos2d-x/external/glfw3/include/mac',
    '-I/Users/guanghui/cocos2d-x/external/jpeg/include/mac',
    '-I/Users/guanghui/cocos2d-x/external/lua',
    '-I/Users/guanghui/cocos2d-x/external/lua/lua',
    '-I/Users/guanghui/cocos2d-x/external/lua/tolua',
    '-I/Users/guanghui/cocos2d-x/external/png/include/mac',
    '-I/Users/guanghui/cocos2d-x/external/recast',
    '-I/Users/guanghui/cocos2d-x/external/recast/..',
    '-I/Users/guanghui/cocos2d-x/external/tiff/include/mac',
    '-I/Users/guanghui/cocos2d-x/external/tinyxml2',
    '-I/Users/guanghui/cocos2d-x/external/unzip',
    '-I/Users/guanghui/cocos2d-x/external/webp/include/mac',
    '-I/Users/guanghui/cocos2d-x/external/websockets/include/mac',
    '-I/Users/guanghui/cocos2d-x/external/xxhash',
    '-I/Users/guanghui/cocos2d-x/external/xxtea',
    '-I/Users/guanghui/cocos2d-x/external/zlib/include',
    '-I/Users/guanghui/cocos2d-x/tests/cpp-tests/Classes',
    '-I/Users/guanghui/cocos2d-x/tests/js-tests/project/../../../cocos/audio/include',
    '-I/Users/guanghui/cocos2d-x/tests/js-tests/project/../../../cocos/base',
    '-I/Users/guanghui/cocos2d-x/tests/js-tests/project/../../../cocos/editor-support',
    '-I/Users/guanghui/cocos2d-x/tests/js-tests/project/../../../cocos/scripting/js-bindings/auto',
    '-I/Users/guanghui/cocos2d-x/tests/js-tests/project/../../../cocos/scripting/js-bindings/manual',
    '-I/Users/guanghui/cocos2d-x/tests/js-tests/project/../../../external/chipmunk/include/chipmunk',
    '-I/Users/guanghui/cocos2d-x/tests/js-tests/project/../../../external/spidermonkey/include/mac',
    '-I/Users/guanghui/cocos2d-x/tests/js-tests/project/Classes',
    '-I/Users/guanghui/cocos2d-x/tests/lua-empty-test/project/../../../cocos/scripting/lua-bindings/manual',
    '-I/Users/guanghui/cocos2d-x/tests/lua-empty-test/project/../../../external/lua/lua',
    '-I/Users/guanghui/cocos2d-x/tests/lua-empty-test/project/../../../external/lua/tolua',
    '-I/Users/guanghui/cocos2d-x/tests/lua-empty-test/project/Classes',
    '-I/Users/guanghui/cocos2d-x/tests/lua-tests/project/../../../cocos/scripting/lua-bindings/auto',
    '-I/Users/guanghui/cocos2d-x/tests/lua-tests/project/../../../cocos/scripting/lua-bindings/manual',
    '-I/Users/guanghui/cocos2d-x/tests/lua-tests/project/../../../external/lua-DCC_ENABLE_BOX2D_INTEGRATION=0',
    '-I/Users/guanghui/cocos2d-x/tests/lua-tests/project/../../../external/lua/lua',
    '-I/Users/guanghui/cocos2d-x/tests/lua-tests/project/../../../external/lua/tolua',
    '-I/Users/guanghui/cocos2d-x/tests/lua-tests/project/Classes',
    '-Wall',
    '-Wextra',
    '-Wno-deprecated-declarations',
    '-Wno-reorder',
    '-std=c++11',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

